# Generated by Django 4.0.4 on 2022-06-10 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userstudents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserStudents',
            new_name='UserStudent',
        ),
    ]
